05_django/07_Static_files/django_ws_7_2/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

05_django/07_Static_files/django_ws_7_2/inmoongram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

05_django/07_Static_files/django_ws_7_2/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=250)
    image = models.ImageField(blank=True)
    image_description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_public = models.BooleanField(default=True)

05_django/07_Static_files/django_ws_7_2/articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = '__all__'

05_django/07_Static_files/django_ws_7_2/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/create.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'articles/update.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

05_django/07_Static_files/django_ws_7_2/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>게시글 생성 페이지</h1>

  <form method="POST" action="{% url "articles:create" %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="CREATE">
  </form>
  <a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock content %}

05_django/07_Static_files/django_ws_7_2/articles/templates/articles/detail.html
{% extends 'base.html' %}


{% block content %}
  <h1>게시글 상세 페이지</h1>

  <p><span>{{ article.pk }}번 게시글 | </span> {{ article.title }}</p>
  <p>작성 시간 : {{ article.created_at }}</p>
  <hr>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="{{ article.image_description }}">  
  {% endif %}
  <p>{{ article.content }}</p>
  <hr>
  <a href="{% url "articles:update" article.pk %}">[update]</a>
  <form action="{% url "articles:delete" article.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  <a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock content %}

05_django/07_Static_files/django_ws_7_2/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>나만의 SNS 서비스</h1>
  <a href="{% url 'articles:create' %}">[CREATE]</a>

  <ul>
    {% for article in articles %}
    <a href="{% url 'articles:detail' article.pk%}">
      {% if article.image  %}
      <img src="{{ article.image.url }}" alt="{{ article.image_description }}">
      {% endif %}
      <p>{{ article.title }}</p>
    </a>
    <hr>
    {% endfor %}
  </ul>
{% endblock content %}

05_django/07_Static_files/django_ws_7_2/articles/templates/articles/update.html
{% extends "base.html" %}

{% block content %}
  <h1>게시글 수정 페이지</h1>
  <form action="{% url "articles:update" article.pk %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="UPDATE">
  </form>
  <a href="{% url "articles:index" %}">[BACK]</a>
{% endblock content %}